### ISSUE TITLE
After changing the profile picture, click Back but not save. Need to display the avatar before the change

### ISSUE THREAD

**Issue by xuliting** [elastos/Elastos.Trinity.DApps.DID#79] opened 2020-10-27 04:56 UTC

**Comment by dchagastelles** [comment] 2020-10-27 19:02
Please check #69 issue. That's the same issue and we asked for clarification on that.

**Comment by kpachhai** [comment] 2020-10-28 00:30
Closing this issue as it's a duplicate of #69

**Closed by kpachhai** 2020-10-28 00:30 UTC
Labels: bug
